FROM python:3.11-slim

WORKDIR /code

# COPY from the root of the context (which is now BASEPRO)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# COPY only the 'app' directory contents into the container
COPY . .

EXPOSE 8000

# The CMD is relative to the WORKDIR, so it's still correct
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]